# Banco de dados (container sams-db do docker-compose.yml)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:postgres}
quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5435/sams}
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.devservices.enabled=false

# Cria/atualiza as tabelas a partir das entidades
quarkus.hibernate-orm.schema-management.strategy=update
